### ISSUE TITLE
Provide a Vagrant environment to give Modern C++ a try (without too much install hassle)

### ISSUE THREAD

**Issue by s-celles** [till213/ModernCPP#1]
Hello,

I did some C++ (very few) 15 years ago (with Qt) and wanted to give a try to "Modern C++".
Working with Windows I would prefer not to install a C++ compiler and CMake but work in a virtualized environment using Vagrant https://www.vagrantup.com/ (installed using Chocolatey https://chocolatey.org/)

Here is my `Vagrantfile`
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    hostname = "cpp.box"

    # Box
    config.vm.box = "ubuntu/impish64"

    # Shared folder
    config.vm.synced_folder ".", "/srv"

    # Change directory to shared folder directory when connecting using vagrant ssh
    config.ssh.extra_args = ["-t", "cd /srv; bash --login"]

    # Setup
    config.vm.provision "setup", type: "shell", inline: <<-SHELL
        touch .hushlogin
        if ! grep -q "cd /srv" ~/.bashrc ; then 
            echo "cd /srv" >> ~/.bashrc 
        fi
        hostnamectl set-hostname #{hostname}
        apt-get update --fix-missing
        apt-get install -q -y build-essential libreadline-dev unzip g++ make cmake git curl vim
    SHELL

    # Lang
    ## Cpp
    #config.vm.provision "cpp", type: "shell", inline: <<-SHELL
    #    # compiling all examples
    #    make
    #SHELL

end
```

I did

`vagrant up`

to build the virtualized dev machine (Ubuntu Impish) and 

`vagrant ssh`

to log in

inside the box I did

```
$ make
cd build && cmake ../.
-- PLATFORM="Linux"
CMake Error at src/language/CMakeLists.txt:4 (add_subdirectory):
  The source directory

    /srv/src/language/CMakeFiles

  does not contain a CMakeLists.txt file.


CMake Error at src/templates/CMakeLists.txt:5 (add_subdirectory):
  The source directory

    /srv/src/templates/CMakeFiles

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "/srv/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:18: cmakestep] Error 1
```

Any idea what is wrong?

Thanks for your help!
(You can provide a Vagrantfile for others users if you want (inspired by this one or an other one)

Kind regards

**Comment by till213** [comment]
Hello,

Thank you for your interest in this little project. To put it into context: all examples are derived from the example code in the book "C++17 - Praxiswissen zum neuen Standard" by Peter Pohmann. I simply extended the code fragments to "generate a compileable executable" and annotated the code (essentially what was described in the text of the book).

That being said, the project is "on hold" for now, as I moved focus to one of my other projects again - but your issue motivated me to add a couple of more examples, and complete some README files (especially with the info about the book!).

> I did some C++ (very few) 15 years ago (with Qt) and wanted to give a try to "Modern C++".

Well, hello there: that pretty much fits my own "profile" as well ;)

Now to your question:

> CMake Error at src/language/CMakeLists.txt:4 (add_subdirectory):
>   The source directory
> 
>     /srv/src/language/CMakeFiles
> 
>   does not contain a CMakeLists.txt file.

This issue is generated from the following ./src/language/CMakeLists.txt content (and in analogy in the 'templates' subdirectory as well):

```
file(GLOB sub-dir *)
foreach(dir ${sub-dir})
if(IS_DIRECTORY ${curdir}/${dir})
  add_subdirectory(${dir})
endif()
endforeach()
```

Now what this **foreach** loop is supposed to do is to add each subdirectory (**add_subdirectory**) to the CMake setup, by iterating over each file in the current directory. The **IS_DIRECTORY** directive (?) is supposed to only add directories (but not files).

Apparently this is exactly what is going wrong in your context, as an attempt is made to add the subdirectory "CMakeFiles".

And just now I realised that CMakeFiles != CMakeLists.txt (I initially thought that CMakeLists.txt was mistaken to be a directory).

CMakeFiles is not part of the repository: it seems that this is generated by some CMake step (?). However I can confirm that this CMake setup works for me on both Mac (with the CMake installation that comes with the default Qt binary installation) and - just now confirmed - on Ubuntu 20.04. In fact, running "make" in the top-level directory doesn't seem to cause a CMakeFIles directory being created in the _original_ source subfolder (and yes, there is a Makefile provided in the top-level directory which does essentially what you did with "mkdir build; cd build; cmake ..." - for convencience).

Aha, and now we're getting closer: I just checked the build directory (still on Ubuntu), and there is indeed such a CMakeFiles subdirectory generated, but located here:

./build/src/language/CMakeFiles

So I _assume_ that you accidentally once triggered a build in the original source directory. You should be able to simply check out the project again (or somehow remove all generated sources - a "git diff" should help here) and try again, but this time make sure that you are in the proper "build" directory ;)

Comparing with the "plain vanilla" source tree should also help identify the (generated) files and directories which do not belong there:

https://github.com/till213/ModernCPP/tree/main/src/language

P.S. I am not a Cmake expert either - as a matter of fact the "foreach" loop discussed above does not work on Windows (can't quite remember the reasons right now), at least not with the MinGW environment that comes with the stock Qt binary installation (Qt 5.15.2 - perhaps it works better with MinGW / Cmake that comes with the latest Qt Creator / Qt 6.x).

But as the source is more meant to be "a reminder of C++17 features" and hence expected to be read and studied than actually executed I didn't spend too much time yet on that Cmake / Windows matter ;)

**Comment by till213** [comment]
Oh, and since I've mentioned Qt a couple of times: that's just me being lazy to setup a "development environment", especially on Windows: "install Qt + Qt Creator + MinGW" and you have all you need to develop (and I use Qt in other projects anyway).

But just to say that for this particular project - which is about "pure C++17" after all - there is absolutely no dependency on Qt. Just Cmake and a C++17 compliant compiler obviously ;)

**Comment by till213** [comment]
Sorry, I actually just realised now that you (correctly) triggered the build by entering "make".

This will use the Makefile here:

https://github.com/till213/ModernCPP/blob/main/Makefile

and it will essentially:

* Check if the subdirectory "build" exists, and if not create it (mkdir build)
* Cd into that build directory and start the actual compilation therein, by calling Cmake with the corresponding options

(In fact, I copied this Makefile from somewhere)

This _should_ prevent that the original source tree is "polluted" with Cmake generated build files and directories (such as the CMakeFiles directory, which does indeed appear in my build directory as well!).

But somehow in your case that CMakeFiles directory ended up in the "original" source tree.

I hope this helps you solve this issue. Again, my best guess would be that you accidentally called "cmake" from within the top-level project directory. Or perhaps the creation of the "build" subdirectory failed and compilation simply continued in the top-level project directory?

In any case, this should give you some hints to investigate further. Let me know if the problem persists!

**Comment by till213** [comment]
Just for the record: the CMake project now also properly works on Windows. There was a "copy & paste" mistake in the CMakeLists.txt which would iterate over all files: it used an uninitialised (and not required anymore) variable which didn't harm on Unix-like systems (//some/path is still equal to the correct /some/path), but generated an invalid path on Windows (/C:/Some/Path/Is/Invalid).

This has just been fixed.
